apiVersion: v1
kind: Service
metadata:
  name: example_app_service
  namespace: test
  labels:
    app: example_app
spec:
  type: LoadBalancer
  ports:
  - port: 8088
    targetPort: 8088
  selector:
    role: example_app
