apiVersion: apps/v1
kind: Deployment
metadata:
  name: {DEPLOYMENT_NAME}
  namespace: {NAMESPACE}
spec:
  replicas: 1
  selector:
    matchLabels:
      role: {DEPLOYMENT_NAME}
  template:
    metadata:
      labels:
        role: {DEPLOYMENT_NAME}
    spec:
      containers:
      - name: {DEPLOYMENT_NAME}
        image: {IMAGE}
        imagePullPolicy: Always
        resources:
        ports:
        - containerPort: 1003
        envFrom:
        - configMapRef:
            name: {CONFIGMAP_NAME}
        - secretRef:
            name: {SECRET_NAME}
      dnsPolicy: Default
