apiVersion: v1
kind: Service
metadata:
  name: {SERVICE_NAME}
  namespace: {NAMESPACE}
  labels:
    app: {DEPLOYMENT_NAME}
spec:
  type: LoadBalancer
  ports:
  - port: {PORT}
    targetPort: {TARGET_PORT}
  selector:
    role: {DEPLOYMENT_NAME}
